---
layout: post
title: ES6 - Promise 对象
categories: blog
tags:
  - ES6
  - Promise
---

> 本文是对[《ECMAScript 6 入门 - Promise 对象》](https://es6.ruanyifeng.com/#docs/promise)一章中知识点的摘录，请访问原文，获取更多详细信息。

## 一、Promise 的含义

Promise 是 ES6 中新增的一种异步编程的解决方案，Promise 可以理解为一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。

Promise 对象有以下两个特点。

- **对象的状态不受外界影响**。Promise 对象代表一个异步操作，有三种状态：`pending`（进行中）、`fulfilled`（已成功）和 `rejected`（已失败）。只有异步操作的结果，可以决定当前是哪种状态，任何其他操作都无法改变这个状态。
- **一旦状态改变，就不会再变**。Promise 对象的状态改变，只有两种可能：从 `pending` 变为 `fulfilled` 和从 `pending` 变为 `rejected`。只要这两种情况发生，就会一直保持这个结果，这时就称为 `resolved`（已定型）。

<!-- ```javascript
const promise = new Promise((resolve, reject) => {
  resolve('success');
  reject('error');
  resolve('another success');
});

promise
  .then(value => console.log(value))
  .catch(error => console.log(error))
// success
```

上面的代码，只会输出 `success`。因为 Promise 的状态一旦改变，就无法变为其他状态。 -->

Promise 也有一些缺点。

- 无法取消 Promise：一旦新建它就会立即执行，无法中途取消。
- 如果不设置回调函数，Promise 内部抛出的错误，不会反应到外部。
- 当处于 `pending` 状态时，无法得知目前进展到哪个阶段（刚刚开始还是即将完成）。

## 二、基本用法

Promise 构造函数接受一个函数作为参数，该函数的两个参数分别是 `resolve` 和 `reject`。

`resolve` 函数的作用是，将 Promise 对象的状态从从 `pending` 变为 `resolved`，在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；`reject` 函数的作用是，将 Promise 对象的状态从 `pending` 变为 `rejected`，在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

Promise 实例生成以后，可以用 `then` 方法分别指定 `resolved` 状态和 `rejected` 状态的回调函数。`then` 方法可以接受两个回调函数作为参数。第一个回调函数是 Promise 对象的状态变为 `resolved` 时调用，第二个回调函数是 Promise 对象的状态变为 `rejected` 时调用。

- **Promise 新建后会立即执行**。

  ```javascript
  const promise = new Promise((resolve, reject) => {
    console.log('Promise');
    resolve();
  });

  promise.then(() => {
    console.log('resolved.');
  });

  console.log('Hi!');
  // Promise
  // Hi!
  // resolved.
  ```

- **调用 `resolve` 或 `reject` 并不会终结 Promise 的参数函数的执行**。一般来说，调用 `resolve` 或 `reject` 以后，Promise 的使命就完成了，后继操作应该放到 `then` 方法里面，而不应该直接写在 `resolve` 或 `reject` 的后面。所以，最好在它们前面加上 `return` 语句，这样就不会有意外。

  ```javascript
  new Promise((resolve, reject) => {
    resolve(1);
    console.log(2);
  }).then(r => {
    console.log(r);
  });
  // 2
  // 1

  new Promise((resolve, reject) => {
    return resolve(1);
    // 后面的语句不会执行
    console.log(2);
  })
  ```

## 三、Promise.prototype.then()

### 1. Promise 的值穿透

Promise 的值穿透是指在 Promise 的链式调用中，如果某个 `then` 方法没有为其参数（即 `onFulfilled` 或 `onRejected`）提供处理函数，Promise 的值会自动穿透到下一个 `then` 方法中。Promise 发生值穿透的原因，是由于 `Promise.then` 或者 `Promise.catch` 方法接受的参数类型决定的。如果 `then` 方法接受的不是函数，就会发生值穿透。Promise 的值穿透分为以下几种情况。

- 如果 `Promise.then` 方法没有回调函数，那么，之前 Promise 对象的值，会透传到之后的 `then` 方法中。

  ```javascript
  Promise.resolve(42)
    .then() // 没有提供 onFulfilled 处理函数
    .then(value => {
      console.log(value);
    });
  // 42
  ```

- 如果 `Promise.then` 方法的回调函数没有返回值，此时，当前 `then` 方法的返回值，会被认为是 `undefined`，并且会被之后的 `then` 方法捕获。

  ```javascript
  Promise.resolve(42)
    .then(value => {
      console.log(value);
    })
    .then(value => {
      console.log(value);
    });
  // 42
  // undefined
  ```

- 如果 `Promise.then` 方法的回调函数有返回值，则会被之后的 `then` 方法捕获。

  ```javascript
  Promise.resolve(42)
    .then(value => {
      console.log(value);
      return 43;
    })
    .then(value => {
      console.log(value);
    });
  // 42
  // 43
  ```

### 2. Promise 的异常穿透

Promise 的异常穿透是指在 Promise 链中，如果某个 `then` 方法没有为其参数（即 `onRejected`）提供错误处理函数，Promise 的错误会自动穿透到下一个 `catch` 方法中，或下一个带有 `onRejected` 的 `then` 方法中。

```javascript
Promise.reject(new Error("Something went wrong"))
.then(value => {
  // 没有提供 onRejected 处理函数
  console.log(value);
})
  .catch(error => {
    console.error(error.message);
  });
// Something went wrong
```

如果 Promise 抛出的错误，被 `then` 方法的 `onRejected` 捕获，那么，错误不再被之后的 `catch` 方法捕获。

```javascript
Promise.reject(new Error("Something went wrong"))
.then(
  value => {}, 
  error => {
    console.log('In then error: ', error);
  })
  .catch(error => {
    console.error('In catch error: ', error.message);
  });
// In then error:  Error: Something went wrong
```

## 四、Promise.prototype.catch()

`catch` 方法是 `.then(null | undefined, onRejected)` 的别名，用于指定发生错误时的回调函数。

- Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个 `catch` 语句捕获。
- 跟传统的 `try/catch` 代码块不同的是，如果没有使用 `catch()` 方法指定错误处理的回调函数，**Promise 对象抛出的错误不会传递到外层代码**。
- `catch()` 方法返回的还是一个 Promise 对象，因此后面还可以接着调用 `then()` 方法。

## 五、Promise.prototype.finally()

`finally` 方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。`finally` 方法会返回一个等效的 Promise 对象。`finally` 本质上是 `then` 方法的特例。它的实现也很简单。

```javascript
Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  => P.resolve(callback()).then(() => value),
    reason => P.resolve(callback()).then(() => { throw reason })
  );
};
```

## 六、Promise.all()、Promise.any()、Promise.race()、Promise.allSettled()

这四个方法都用于将多个 Promise 实例包装成一个新的 Promise 实例。

- `Promise.all` 方法会在所有实例对象 `resolved` 或任何一个实例对象 `rejected` 之后兑现。如果作为参数的 Promise 实例自己定义了 `catch` 方法，那么如果它 `rejected`，并不会触发 `Promise.all` 的 `catch` 方法。

  ```javascript
  const p1 = new Promise((resolve, reject) => {
    resolve('hello');
  })
  .then(result => result)
  .catch(e => e);

  const p2 = new Promise((resolve, reject) => {
    throw new Error('报错了');
  })
  .then(result => result)
  .catch(e => e);

  Promise.all([p1, p2])
  .then(result => console.log(result))
  .catch(e => console.log(e));
  // ["hello", Error: 报错了]
  ```

  上面代码中，`p1` 会 `resolved`，`p2` 首先会 `rejected`，但是 `p2` 有自己的 `catch` 方法，该方法返回的是一个新的、且返回值为被 Promise 包裹的 Error 类型的 Promise 实例，`p2` 指向的实际上是这个实例。该实例执行完 `catch` 方法后，也会变成 `resolved`，导致 `Promise.all` 方法参数里面的两个实例都会 `resolved`，因此会调用 `then` 方法指定的回调函数，而不会调用 `catch` 方法指定的回调函数。如果 `p2` 没有自己的 `catch` 方法，就会调用 `Promise.all` 的 `catch` 方法。

- `Promise.any` 方法在所有实例对象 `rejected` 或者任何一个 Promise 对象 `resolved` 之后兑现。`Promise.any` 抛出的错误是一个 AggregateError 实例。
- `Promise.race` 方法在任意一个实例对象 `resolved` 或 `rejected` 之后兑现。
- `Promise.allSettled` 方法在所有实例对象 `resolved` 或 `rejected` 之后兑现。

  该方法返回的新的实例对象，一旦发生状态变更，状态总是 `fulfilled`，不会变成 `rejected`。

  ```javascript
  const allSettledPromise = Promise.allSettled([Promise.resolve(42), Promise.reject(-1)]);
  allSettledPromise.then(function (results) {
    console.log(results);
  });
  // [
  //    { status: 'fulfilled', value: 42 },
  //    { status: 'rejected', reason: -1 }
  // ]
  ```

  上面代码中，`Promise.allSettled()` 的返回值 `allSettledPromise`，状态只可能变成 `fulfilled`。`results` 的每个成员是一个对象，对象的格式是固定的，对应异步操作的结果。

## 七、Promise.resolve()

`Promise.resolve` 方法返回一个状态为 `resolved` 的新的 Promise。它的参数分成四种情况。

- 参数是 Promise 实例：此时 `Promise.resolve` 将不做任何修改、原封不动地返回这个实例。
- 参数是 `thenable` 对象：`thenable` 对象指的是具有 `then` 方法的对象，`Promise.resolve` 方法会将这个对象转为 Promise 对象，然后立即执行 `thenable` 对象的 `then` 方法。
- 参数不是具有 `then` 方法的对象，或根本就不是对象：如果参数是原始值，或者是不具有 `then` 方法的对象，则 `Promise.resolve` 方法返回一个新的 Promise 对象，状态为 `resolved`。
- 不带有任何参数：此时直接返回一个状态为 `resolved` 的 Promise 对象。立即 `resolve` 的 Promise 对象，是在本轮“事件循环”（event loop）的结束时执行，而不是在下一轮“事件循环”的开始时。

## 八、Promise.reject()

`Promise.reject` 方法返回一个状态为 `rejected` 的 Promise 对象。

## 九、Promise.try()

`Promise.try` 方法接受一个回调函数（比如，带有返回值、抛出错误、同步或者异步等），然后将其结果包装为一个 Promise。可以认为，`Promise.try` 就是模拟的 `try` 代码块。

注意，`Promise.try` 目前只是一个 [提案](https://github.com/tc39/proposal-promise-try)，还未纳入正式的 ES 标准。

## 十、参考

- 阮一峰，[Promise 对象](https://es6.ruanyifeng.com/#docs/promise)
